// ─────────────────────────────────────────────────────────────
//  gm_icons.h — GaggiMate "Nothing" theme icon set
//  10 monochrome line icons, recolorable at runtime.
//
//  Adapted for this codebase: LVGL v8 (8.4.0) API.
//
//  Two ways to use them — both are wired below:
//
//  ▸ ROUTE B · IMAGE (A8)  — ACTIVE / default
//      gm_ic_<name> are LV_IMG_CF_ALPHA_8BIT masks generated by
//      assets/gm-icons/gen_a8_images.py from the 96px PNG masters.
//      Use with lv_img / imgbtn / bg_img and tint at runtime via
//      lv_obj_set_style_img_recolor(+_opa) (or the bg_img_recolor
//      variants). No font toolchain required — this is what the
//      screens use today.
//
//  ▸ ROUTE A · SYMBOL FONT — optional (recolor via text color)
//      Set GM_USE_ICON_FONT to 1 once the font is generated:
//        1. Import assets/gm-icons/svg/*.svg into IcoMoon
//           (https://icomoon.io), assign each the codepoint below,
//           export gm_icons.ttf.
//        2. lv_font_conv --font gm_icons.ttf --size 28 --bpp 4 \
//             --format lvgl --range 0xE001-0xE00A \
//             -o gm_icons_28.c --force-fast-kern-format
//           (repeat at --size 16 for gm_icons_16.c)
//        3. Add the generated .c files to filelist.txt + CMakeLists.txt,
//           use lv_label + the GM_SYM_* strings, and set color with
//           lv_obj_set_style_text_color() (knockout = the bg color).
// ─────────────────────────────────────────────────────────────
#ifndef GM_ICONS_H
#define GM_ICONS_H

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

// Flip to 1 to use the symbol font (Route A) instead of A8 images.
#ifndef GM_USE_ICON_FONT
#define GM_USE_ICON_FONT 0
#endif

// Codepoints (Private Use Area). Assign these in IcoMoon for Route A.
#define GM_ICON_POWER  0xE001
#define GM_ICON_CUP    0xE002
#define GM_ICON_STEAM  0xE003
#define GM_ICON_DROP   0xE004
#define GM_ICON_WIFI   0xE005
#define GM_ICON_BT     0xE006
#define GM_ICON_SUN    0xE007
#define GM_ICON_THERMO 0xE008
#define GM_ICON_SCALE  0xE009
#define GM_ICON_BACK   0xE00A

// ── ROUTE A · symbol font ────────────────────────────────────
// UTF-8 encodings of the codepoints above, for lv_label_set_text().
#define GM_SYM_POWER   "\xEE\x80\x81"
#define GM_SYM_CUP     "\xEE\x80\x82"
#define GM_SYM_STEAM   "\xEE\x80\x83"
#define GM_SYM_DROP    "\xEE\x80\x84"
#define GM_SYM_WIFI    "\xEE\x80\x85"
#define GM_SYM_BT      "\xEE\x80\x86"
#define GM_SYM_SUN     "\xEE\x80\x87"
#define GM_SYM_THERMO  "\xEE\x80\x88"
#define GM_SYM_SCALE   "\xEE\x80\x89"
#define GM_SYM_BACK    "\xEE\x80\x8A"

#if GM_USE_ICON_FONT
LV_FONT_DECLARE(gm_icons_28); // chips / settings rows
LV_FONT_DECLARE(gm_icons_16); // status bar (optional smaller cut)
#endif

// ── ROUTE B · A8 images (active) ─────────────────────────────
// 48x48 LV_IMG_CF_ALPHA_8BIT masks; recolor via (bg_)img_recolor.
LV_IMG_DECLARE(gm_ic_power);
LV_IMG_DECLARE(gm_ic_cup);
LV_IMG_DECLARE(gm_ic_steam);
LV_IMG_DECLARE(gm_ic_drop);
LV_IMG_DECLARE(gm_ic_wifi);
LV_IMG_DECLARE(gm_ic_bt);
LV_IMG_DECLARE(gm_ic_sun);
LV_IMG_DECLARE(gm_ic_thermo);
LV_IMG_DECLARE(gm_ic_scale);
LV_IMG_DECLARE(gm_ic_back);

#ifdef __cplusplus
}
#endif

#endif // GM_ICONS_H
