// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_NiceWhite[2] = {0xF6E8D5, 0x231814};
const ui_theme_variable_t _ui_theme_alpha_NiceWhite[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Dark[2] = {0x140E0C, 0xF7EFE7};
const ui_theme_variable_t _ui_theme_alpha_Dark[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_SemiDark[2] = {0xA88F7B, 0x6F5B50};
const ui_theme_variable_t _ui_theme_alpha_SemiDark[2] = {408, 255};

const ui_theme_variable_t _ui_theme_color_Progress[2] = {0xD2A56D, 0xB78347};
const ui_theme_variable_t _ui_theme_alpha_Progress[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Heating[2] = {0xE97A33, 0xB95B24};
const ui_theme_variable_t _ui_theme_alpha_Heating[2] = {255, 255};

// Nothing theme colors — all three slots use identical Nothing values
const ui_theme_variable_t _ui_theme_color_NothingBase[3]     = {0x000000, 0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_color_NothingTrack[3]    = {0x1A1A1A, 0x1A1A1A, 0x1A1A1A};
const ui_theme_variable_t _ui_theme_color_NothingContent[3] = {0xE8E8E8, 0xE8E8E8, 0xE8E8E8};
const ui_theme_variable_t _ui_theme_color_NothingRed[3]     = {0xD71921, 0xD71921, 0xD71921};
const ui_theme_variable_t _ui_theme_color_NothingMuted[3]   = {0x888888, 0x888888, 0x888888};
const ui_theme_variable_t _ui_theme_color_NothingDisabled[3] = {0x5A5A5A, 0x5A5A5A, 0x5A5A5A};

uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx) {
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}
