/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "comms.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(gaggimate_spike_SensorData, gaggimate_spike_SensorData, AUTO)


PB_BIND(gaggimate_spike_Error, gaggimate_spike_Error, AUTO)


PB_BIND(gaggimate_spike_BrewButton, gaggimate_spike_BrewButton, AUTO)


PB_BIND(gaggimate_spike_SteamButton, gaggimate_spike_SteamButton, AUTO)


PB_BIND(gaggimate_spike_AutotuneResult, gaggimate_spike_AutotuneResult, AUTO)


PB_BIND(gaggimate_spike_VolumetricMeasurement, gaggimate_spike_VolumetricMeasurement, AUTO)


PB_BIND(gaggimate_spike_TofMeasurement, gaggimate_spike_TofMeasurement, AUTO)


PB_BIND(gaggimate_spike_Capabilities, gaggimate_spike_Capabilities, AUTO)


PB_BIND(gaggimate_spike_SystemInfo, gaggimate_spike_SystemInfo, AUTO)


PB_BIND(gaggimate_spike_SimpleOutput, gaggimate_spike_SimpleOutput, AUTO)


PB_BIND(gaggimate_spike_AdvancedOutput, gaggimate_spike_AdvancedOutput, AUTO)


PB_BIND(gaggimate_spike_AltControl, gaggimate_spike_AltControl, AUTO)


PB_BIND(gaggimate_spike_Ping, gaggimate_spike_Ping, AUTO)


PB_BIND(gaggimate_spike_PidSettings, gaggimate_spike_PidSettings, AUTO)


PB_BIND(gaggimate_spike_PumpModelCoeffs, gaggimate_spike_PumpModelCoeffs, AUTO)


PB_BIND(gaggimate_spike_AutotuneRequest, gaggimate_spike_AutotuneRequest, AUTO)


PB_BIND(gaggimate_spike_PressureScale, gaggimate_spike_PressureScale, AUTO)


PB_BIND(gaggimate_spike_Tare, gaggimate_spike_Tare, AUTO)


PB_BIND(gaggimate_spike_LedControl, gaggimate_spike_LedControl, AUTO)



