// Originally generated by SquareLine Studio (LVGL 8.3.11). Rebuilt for the
// Nothing theme in CAR-294 — declarations preserved for ABI compatibility
// with DefaultUI.cpp / ui_events.cpp.

#ifndef UI_GRINDSCREEN_H
#define UI_GRINDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GrindScreen
extern void ui_GrindScreen_screen_init(void);
extern void ui_GrindScreen_screen_destroy(void);
extern void ui_event_GrindScreen(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen;
extern lv_obj_t *ui_GrindScreen_dials;
extern void ui_event_GrindScreen_ImgButton2(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen_ImgButton2;
extern lv_obj_t *ui_GrindScreen_contentPanel7;
extern lv_obj_t *ui_GrindScreen_mainLabel7;
extern void ui_event_GrindScreen_startButton(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen_startButton;
extern lv_obj_t *ui_GrindScreen_targetContainer;
extern lv_obj_t *ui_GrindScreen_targetDuration;
extern void ui_event_GrindScreen_upDurationButton(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen_upDurationButton;
extern void ui_event_GrindScreen_downDurationButton(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen_downDurationButton;
extern lv_obj_t *ui_GrindScreen_targetSymbol;
extern void ui_event_GrindScreen_modeSwitch(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen_modeSwitch;
extern lv_obj_t *ui_GrindScreen_volumetricButton;
extern lv_obj_t *ui_GrindScreen_weightLabel;
// CUSTOM VARIABLES
extern lv_obj_t *uic_GrindScreen_dials_tempGauge;
extern lv_obj_t *uic_GrindScreen_dials_tempTarget;
extern lv_obj_t *uic_GrindScreen_dials_pressureGauge;
extern lv_obj_t *uic_GrindScreen_dials_pressureTarget;
extern lv_obj_t *uic_GrindScreen_dials_pressureText;
extern lv_obj_t *uic_GrindScreen_dials_tempText;

// CAR-294: Nothing-theme palette pass. DefaultUI's applyScreenVisualLanguage
// calls this to recolor tracked themable children for UI_THEME_LIGHT support
// (the dark default GM_* tokens go invisible against a light bg). Mirrors
// ui_BrewScreen_apply_palette() (CAR-293).
extern void ui_GrindScreen_apply_palette(lv_color_t text, lv_color_t muted,
                                         lv_color_t buttonSurface, lv_color_t accent,
                                         lv_color_t kickerTone);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
