#!/usr/bin/env python3
"""
Generate LVGL v8 ALPHA_8BIT image sources for the GaggiMate "Nothing" icon set.

Input : assets/gm-icons/png/<name>.png   (96x96 white-on-transparent masters)
Output: src/display/ui/default/lvgl/images/gm_ic_<name>.c

The icons are monochrome line art. We keep only the alpha channel and emit it as
LV_IMG_CF_ALPHA_8BIT (1 byte/pixel). LVGL renders every pixel in the widget's
`(bg_)img_recolor` color, modulated by this alpha — so the same asset can be
tinted to any color at runtime (white, mode accent, knockout, etc.).

Usage:  python assets/gm-icons/gen_a8_images.py [--size 48]
Requires: Pillow
"""
import argparse
import pathlib

from PIL import Image

# Icon -> codepoint (Private Use Area). Mirrors gm_icons.h / Icon Set.html.
ICONS = {
    "power": 0xE001,
    "cup": 0xE002,
    "steam": 0xE003,
    "drop": 0xE004,
    "wifi": 0xE005,
    "bt": 0xE006,
    "sun": 0xE007,
    "thermo": 0xE008,
    "scale": 0xE009,
    "back": 0xE00A,
}

HERE = pathlib.Path(__file__).resolve().parent
PNG_DIR = HERE / "png"
OUT_DIR = HERE.parent.parent / "src" / "display" / "ui" / "default" / "lvgl" / "images"

C_TEMPLATE = """\
// Generated by assets/gm-icons/gen_a8_images.py — do not edit by hand.
// GaggiMate "Nothing" icon set: {name} ({size}x{size}, LV_IMG_CF_ALPHA_8BIT, U+{cp:04X}).
// Monochrome alpha mask; tint at runtime via lv_obj_set_style_(bg_)img_recolor().

#include "../gm_icons.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t gm_ic_{name}_data[] = {{
{data}
}};

const lv_img_dsc_t gm_ic_{name} = {{
    .header.always_zero = 0,
    .header.w = {size},
    .header.h = {size},
    .data_size = sizeof(gm_ic_{name}_data),
    .header.cf = LV_IMG_CF_ALPHA_8BIT,
    .data = gm_ic_{name}_data,
}};
"""


def fmt_bytes(alpha: bytes, per_line: int = 20) -> str:
    lines = []
    for i in range(0, len(alpha), per_line):
        chunk = alpha[i : i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, default=40, help="output icon size in px")
    args = ap.parse_args()
    size = args.size

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, cp in ICONS.items():
        src = PNG_DIR / f"{name}.png"
        img = Image.open(src).convert("RGBA")
        if img.size != (size, size):
            img = img.resize((size, size), Image.LANCZOS)
        alpha = img.split()[3].tobytes()  # A channel, row-major, 1 byte/px
        assert len(alpha) == size * size, (name, len(alpha))
        c = C_TEMPLATE.format(name=name, cp=cp, size=size, data=fmt_bytes(alpha))
        (OUT_DIR / f"gm_ic_{name}.c").write_text(c, encoding="utf-8", newline="\n")
        print(f"  gm_ic_{name}.c  ({size}x{size}, {len(alpha)} bytes alpha)")
    print(f"Wrote {len(ICONS)} icons to {OUT_DIR}")


if __name__ == "__main__":
    main()
